### ISSUE TITLE
gazuaa 표준개발환경 [ airflow ]

### ISSUE THREAD

**Issue by J3llyBe4n** [dduck-sang/gazuaa#1]
## gazuaa 프로덕트를 개발하기 위한 airflow 표준 개발 환경 설치 문서입니다.

- [ ] dockerfile : dockerfile을 통한, custom airflow image 를 빌드
- [ ] docker-compose : .yml file을 통한, airflow components 구축

---

1. airflow 개발환경 

[dockerfile]
airflow 폴더 -> vim dockerfile 생성
```
FROM apache/airflow:2.6.1-python3.8
RUN pip install --user --upgrade pip
RUN pip install mysql-connector
RUN pip install requests
RUN pip install pandas
RUN pip install yfinance
RUN pip install -U finance-datareader
```

docker daemon open 후, cli 환경에서 

`docker build --tag apache/airflow:stock .`

전처리 및 데이터 수집을 위해 필요한 모듈이 설치된 custom image가 생성됩니다.

<img width="637" alt="Screen Shot 2023-06-07 at 11 47 32 AM" src="https://github.com/dduck-sang/gazuaa/assets/23203791/f133025b-768d-4ff1-8b77-00905fe54df3">

airflow폴더 ->  vim docker-compose.yml 

```
version: "3.7"
x-environment: &airflow_environment
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW__WEBSERVER__RBAC=False
x-airflow-image: &airflow_image apache/airflow:stock 
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
  init:
    image: *airflow_image
    depends_on:
      - postgres
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c 'airflow db upgrade && sleep 5 && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'
  webserver:
    image: *airflow_image
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - logs:/opt/airflow/logs
    environment: *airflow_environment
    command: webserver
  scheduler:
    image: *airflow_image
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - logs:/opt/airflow/logs
    environment: *airflow_environment
    command: scheduler

volumes:
  logs:

```

- x-airflow-image: &airflow_image apache/airflow:stock line에 이미지이름을 생성한 custom 이미지 이름으로 바꿔준다.

---

airflow info

web port : 8080
id : admin
pw : admin
executor type : localExecutor

---

추가 필요 모듈이 있는 경우, 댓글에 작성해주시면 반영하겠습니다.
